### PR TITLE
Add install schema

### PR DESCRIPTION
**Pull request by gdespirito**
Add install schema so the table 'webpay_orders_data' is created.

### CODE REVIEW

**Comment by rsantosCL** [comment]
To avoid replicated code, it wouldn't be better to have the table creation code in a single method accessible from `InstallSchema` and `UpgradeSchema`?

**Comment by saengate** [comment]
@gonzunigad I don't see when the class is called. Is that part in another file?

**Comment by gdespirito** [comment]
I'm refactoring the replicated code. Those classess are called internally by Magento on the setup:upgrade command :)

**Comment by gdespirito** [comment]
As every tests takes me about 20 minutes, I did not wanted to refactor the code yet, but i will do it now.

**Comment by rsantosCL** [comment]
You need to add the `Setup` directory to `copy-plugin` shell file in docker directories, in order to apply the database migrations inside docker containers.

**Review by rsantosCL — APPROVED** [review]
👍

**Pull request merged**
